### ISSUE TITLE
format_fig figures go off the edge in Jupyter Books

### ISSUE THREAD

**Issue by nikhilwoodruff** [UBICenter/ubicenter.py#8]
In Jupyter Books, normal figures fit nicely without getting clipped behind the right-hand-side TOC view, but format_fig-ed figures get clipped behind it.

**Comment by MaxGhenis** [comment]
Yeah it's also wider than the text in ubicenter.org, e.g. in https://www.ubicenter.org/womens-day-2021:
![image](https://user-images.githubusercontent.com/6076111/120740511-2d63d800-c4a8-11eb-9472-02b52f0106c3.png)
